var mongoose = require('mongoose');

//Creating a Scheama for Report
var reportSchema = mongoose.Schema({
        date: {type: Date},
        product: [
            {
            name: {type:String, required:'{PATH} is required'},
            quantity: {type:Number, min: 0, required:'{PATH} is required'}
            }
        ]
    },
    {
        timestamps: true
    });

//Create a model based on the above Schema

var Report = mongoose.model('Report', reportSchema);

//create default Prodcuts in the DB if there is no records

function createDefaultReport() {
    Report.find({}).exec(function (err, collection) {
        if (collection.length === 0) {
            Report.create({date: new Date('2017-04-05'), product:[{name: 'Black Plaid Keyhole Front Bell Sleeve Dress', quantity: 50}, {name: 'Black Halter One Shoulder Bodycon Dress', quantity: 24}, {name: 'Black Ripped Drawstring Sweatpants', quantity: 15}, {name: 'Black Contrast Elastic Waist Faux Leather Leggings', quantity: 7}, {name: 'Silver Elastic Fabric Chunky Heel Short Boots', quantity: 5}, {name: 'White V Neck Drop Shoulder Sweater', quantity: 0}, {name: 'Pink Layered Ruffle Sleeve Pullover Sweater', quantity: 0}, {name: 'Green army jacket', quantity: 0}, {name: 'adidas navy bomber jacket', quantity: 0}, {name: 'Chain', quantity: 0}, {name: 'Turtleneck Raglan Sleeve Loose Sweater', quantity: 5}, {name: 'White Lace Overlay Elastic Waist Skirt', quantity: 15}, {name: 'Plaid Back Zipper Pleated Skirt', quantity: 10}]})
            Report.create({date: new Date('2017-04-04'), product:[{name: 'Black Plaid Keyhole Front Bell Sleeve Dress', quantity: 50}, {name: 'Black Halter One Shoulder Bodycon Dress', quantity: 10}, {name: 'Black Ripped Drawstring Sweatpants', quantity: 10}, {name: 'Black Contrast Elastic Waist Faux Leather Leggings', quantity: 10}, {name: 'Silver Elastic Fabric Chunky Heel Short Boots', quantity: 10}, {name: 'White V Neck Drop Shoulder Sweater', quantity: 10}, {name: 'Pink Layered Ruffle Sleeve Pullover Sweater', quantity: 10}, {name: 'Green army jacket', quantity: 10}, {name: 'adidas navy bomber jacket', quantity: 10}, {name: 'Chain', quantity: 10}, {name: 'Turtleneck Raglan Sleeve Loose Sweater', quantity: 10}, {name: 'White Lace Overlay Elastic Waist Skirt', quantity: 10}, {name: 'Plaid Back Zipper Pleated Skirt', quantity: 10}]})
            Report.create({date: new Date('2017-04-03'), product:[{name: 'Black Plaid Keyhole Front Bell Sleeve Dress', quantity: 50}, {name: 'Black Halter One Shoulder Bodycon Dress', quantity: 10}, {name: 'Black Ripped Drawstring Sweatpants', quantity: 10}, {name: 'Black Contrast Elastic Waist Faux Leather Leggings', quantity: 10}, {name: 'Silver Elastic Fabric Chunky Heel Short Boots', quantity: 10}, {name: 'White V Neck Drop Shoulder Sweater', quantity: 10}, {name: 'Pink Layered Ruffle Sleeve Pullover Sweater', quantity: 10}, {name: 'Green army jacket', quantity: 10}, {name: 'adidas navy bomber jacket', quantity: 10}, {name: 'Chain', quantity: 10}, {name: 'Turtleneck Raglan Sleeve Loose Sweater', quantity: 10}, {name: 'White Lace Overlay Elastic Waist Skirt', quantity: 10}, {name: 'Plaid Back Zipper Pleated Skirt', quantity: 10}]})
            Report.create({date: new Date('2017-04-02'), product:[{name: 'Black Plaid Keyhole Front Bell Sleeve Dress', quantity: 50}, {name: 'Black Halter One Shoulder Bodycon Dress', quantity: 10}, {name: 'Black Ripped Drawstring Sweatpants', quantity: 10}, {name: 'Black Contrast Elastic Waist Faux Leather Leggings', quantity: 10}, {name: 'Silver Elastic Fabric Chunky Heel Short Boots', quantity: 10}, {name: 'White V Neck Drop Shoulder Sweater', quantity: 10}, {name: 'Pink Layered Ruffle Sleeve Pullover Sweater', quantity: 10}, {name: 'Green army jacket', quantity: 10}, {name: 'adidas navy bomber jacket', quantity: 10}, {name: 'Chain', quantity: 10}, {name: 'Turtleneck Raglan Sleeve Loose Sweater', quantity: 10}, {name: 'White Lace Overlay Elastic Waist Skirt', quantity: 10}, {name: 'Plaid Back Zipper Pleated Skirt', quantity: 10}]})
            Report.create({date: new Date('2017-04-01'), product:[{name: 'Black Plaid Keyhole Front Bell Sleeve Dress', quantity: 50}, {name: 'Black Halter One Shoulder Bodycon Dress', quantity: 10}, {name: 'Black Ripped Drawstring Sweatpants', quantity: 10}, {name: 'Black Contrast Elastic Waist Faux Leather Leggings', quantity: 10}, {name: 'Silver Elastic Fabric Chunky Heel Short Boots', quantity: 10}, {name: 'White V Neck Drop Shoulder Sweater', quantity: 10}, {name: 'Pink Layered Ruffle Sleeve Pullover Sweater', quantity: 10}, {name: 'Green army jacket', quantity: 10}, {name: 'adidas navy bomber jacket', quantity: 10}, {name: 'Chain', quantity: 10}, {name: 'Turtleneck Raglan Sleeve Loose Sweater', quantity: 10}, {name: 'White Lace Overlay Elastic Waist Skirt', quantity: 10}, {name: 'Plaid Back Zipper Pleated Skirt', quantity: 10}]})
            Report.create({date: new Date('2017-03-31'), product:[{name: 'Black Plaid Keyhole Front Bell Sleeve Dress', quantity: 0}, {name: 'Black Halter One Shoulder Bodycon Dress', quantity: 10}, {name: 'Black Ripped Drawstring Sweatpants', quantity: 10}, {name: 'Black Contrast Elastic Waist Faux Leather Leggings', quantity: 10}, {name: 'Silver Elastic Fabric Chunky Heel Short Boots', quantity: 10}, {name: 'White V Neck Drop Shoulder Sweater', quantity: 10}, {name: 'Pink Layered Ruffle Sleeve Pullover Sweater', quantity: 10}, {name: 'Green army jacket', quantity: 10}, {name: 'adidas navy bomber jacket', quantity: 10}, {name: 'Chain', quantity: 10}, {name: 'Turtleneck Raglan Sleeve Loose Sweater', quantity: 10}, {name: 'White Lace Overlay Elastic Waist Skirt', quantity: 10}, {name: 'Plaid Back Zipper Pleated Skirt', quantity: 10}]})
            Report.create({date: new Date('2017-03-30'), product:[{name: 'Black Plaid Keyhole Front Bell Sleeve Dress', quantity: 0}, {name: 'Black Halter One Shoulder Bodycon Dress', quantity: 10}, {name: 'Black Ripped Drawstring Sweatpants', quantity: 10}, {name: 'Black Contrast Elastic Waist Faux Leather Leggings', quantity: 10}, {name: 'Silver Elastic Fabric Chunky Heel Short Boots', quantity: 10}, {name: 'White V Neck Drop Shoulder Sweater', quantity: 10}, {name: 'Pink Layered Ruffle Sleeve Pullover Sweater', quantity: 10}, {name: 'Green army jacket', quantity: 10}, {name: 'adidas navy bomber jacket', quantity: 10}, {name: 'Chain', quantity: 10}, {name: 'Turtleneck Raglan Sleeve Loose Sweater', quantity: 10}, {name: 'White Lace Overlay Elastic Waist Skirt', quantity: 10}, {name: 'Plaid Back Zipper Pleated Skirt', quantity: 10}]})
            Report.create({date: new Date('2017-03-29'), product:[{name: 'Black Plaid Keyhole Front Bell Sleeve Dress', quantity: 0}, {name: 'Black Halter One Shoulder Bodycon Dress', quantity: 10}, {name: 'Black Ripped Drawstring Sweatpants', quantity: 10}, {name: 'Black Contrast Elastic Waist Faux Leather Leggings', quantity: 10}, {name: 'Silver Elastic Fabric Chunky Heel Short Boots', quantity: 10}, {name: 'White V Neck Drop Shoulder Sweater', quantity: 10}, {name: 'Pink Layered Ruffle Sleeve Pullover Sweater', quantity: 10}, {name: 'Green army jacket', quantity: 10}, {name: 'adidas navy bomber jacket', quantity: 10}, {name: 'Chain', quantity: 10}, {name: 'Turtleneck Raglan Sleeve Loose Sweater', quantity: 10}, {name: 'White Lace Overlay Elastic Waist Skirt', quantity: 10}, {name: 'Plaid Back Zipper Pleated Skirt', quantity: 10}]})
            Report.create({date: new Date('2017-03-28'), product:[{name: 'Black Plaid Keyhole Front Bell Sleeve Dress', quantity: 0}, {name: 'Black Halter One Shoulder Bodycon Dress', quantity: 10}, {name: 'Black Ripped Drawstring Sweatpants', quantity: 10}, {name: 'Black Contrast Elastic Waist Faux Leather Leggings', quantity: 10}, {name: 'Silver Elastic Fabric Chunky Heel Short Boots', quantity: 10}, {name: 'White V Neck Drop Shoulder Sweater', quantity: 10}, {name: 'Pink Layered Ruffle Sleeve Pullover Sweater', quantity: 10}, {name: 'Green army jacket', quantity: 10}, {name: 'adidas navy bomber jacket', quantity: 10}, {name: 'Chain', quantity: 10}, {name: 'Turtleneck Raglan Sleeve Loose Sweater', quantity: 10}, {name: 'White Lace Overlay Elastic Waist Skirt', quantity: 10}, {name: 'Plaid Back Zipper Pleated Skirt', quantity: 10}]})
            Report.create({date: new Date('2017-03-27'), product:[{name: 'Black Plaid Keyhole Front Bell Sleeve Dress', quantity: 0}, {name: 'Black Halter One Shoulder Bodycon Dress', quantity: 10}, {name: 'Black Ripped Drawstring Sweatpants', quantity: 10}, {name: 'Black Contrast Elastic Waist Faux Leather Leggings', quantity: 10}, {name: 'Silver Elastic Fabric Chunky Heel Short Boots', quantity: 10}, {name: 'White V Neck Drop Shoulder Sweater', quantity: 10}, {name: 'Pink Layered Ruffle Sleeve Pullover Sweater', quantity: 10}, {name: 'Green army jacket', quantity: 10}, {name: 'adidas navy bomber jacket', quantity: 10}, {name: 'Chain', quantity: 10}, {name: 'Turtleneck Raglan Sleeve Loose Sweater', quantity: 10}, {name: 'White Lace Overlay Elastic Waist Skirt', quantity: 10}, {name: 'Plaid Back Zipper Pleated Skirt', quantity: 10}]})
            Report.create({date: new Date('2017-03-26'), product:[{name: 'Black Plaid Keyhole Front Bell Sleeve Dress', quantity: 0}, {name: 'Black Halter One Shoulder Bodycon Dress', quantity: 10}, {name: 'Black Ripped Drawstring Sweatpants', quantity: 10}, {name: 'Black Contrast Elastic Waist Faux Leather Leggings', quantity: 10}, {name: 'Silver Elastic Fabric Chunky Heel Short Boots', quantity: 10}, {name: 'White V Neck Drop Shoulder Sweater', quantity: 10}, {name: 'Pink Layered Ruffle Sleeve Pullover Sweater', quantity: 10}, {name: 'Green army jacket', quantity: 10}, {name: 'adidas navy bomber jacket', quantity: 10}, {name: 'Chain', quantity: 10}, {name: 'Turtleneck Raglan Sleeve Loose Sweater', quantity: 10}, {name: 'White Lace Overlay Elastic Waist Skirt', quantity: 10}, {name: 'Plaid Back Zipper Pleated Skirt', quantity: 10}]})
            Report.create({date: new Date('2017-03-25'), product:[{name: 'Black Plaid Keyhole Front Bell Sleeve Dress', quantity: 0}, {name: 'Black Halter One Shoulder Bodycon Dress', quantity: 10}, {name: 'Black Ripped Drawstring Sweatpants', quantity: 10}, {name: 'Black Contrast Elastic Waist Faux Leather Leggings', quantity: 10}, {name: 'Silver Elastic Fabric Chunky Heel Short Boots', quantity: 10}, {name: 'White V Neck Drop Shoulder Sweater', quantity: 10}, {name: 'Pink Layered Ruffle Sleeve Pullover Sweater', quantity: 10}, {name: 'Green army jacket', quantity: 10}, {name: 'adidas navy bomber jacket', quantity: 10}, {name: 'Chain', quantity: 10}, {name: 'Turtleneck Raglan Sleeve Loose Sweater', quantity: 10}, {name: 'White Lace Overlay Elastic Waist Skirt', quantity: 10}, {name: 'Plaid Back Zipper Pleated Skirt', quantity: 10}]})
            Report.create({date: new Date('2017-03-24'), product:[{name: 'Black Plaid Keyhole Front Bell Sleeve Dress', quantity: 0}, {name: 'Black Halter One Shoulder Bodycon Dress', quantity: 10}, {name: 'Black Ripped Drawstring Sweatpants', quantity: 10}, {name: 'Black Contrast Elastic Waist Faux Leather Leggings', quantity: 10}, {name: 'Silver Elastic Fabric Chunky Heel Short Boots', quantity: 10}, {name: 'White V Neck Drop Shoulder Sweater', quantity: 10}, {name: 'Pink Layered Ruffle Sleeve Pullover Sweater', quantity: 10}, {name: 'Green army jacket', quantity: 10}, {name: 'adidas navy bomber jacket', quantity: 10}, {name: 'Chain', quantity: 10}, {name: 'Turtleneck Raglan Sleeve Loose Sweater', quantity: 10}, {name: 'White Lace Overlay Elastic Waist Skirt', quantity: 10}, {name: 'Plaid Back Zipper Pleated Skirt', quantity: 10}]})
            Report.create({date: new Date('2017-03-23'), product:[{name: 'Black Plaid Keyhole Front Bell Sleeve Dress', quantity: 0}, {name: 'Black Halter One Shoulder Bodycon Dress', quantity: 10}, {name: 'Black Ripped Drawstring Sweatpants', quantity: 10}, {name: 'Black Contrast Elastic Waist Faux Leather Leggings', quantity: 10}, {name: 'Silver Elastic Fabric Chunky Heel Short Boots', quantity: 10}, {name: 'White V Neck Drop Shoulder Sweater', quantity: 10}, {name: 'Pink Layered Ruffle Sleeve Pullover Sweater', quantity: 10}, {name: 'Green army jacket', quantity: 10}, {name: 'adidas navy bomber jacket', quantity: 10}, {name: 'Chain', quantity: 10}, {name: 'Turtleneck Raglan Sleeve Loose Sweater', quantity: 10}, {name: 'White Lace Overlay Elastic Waist Skirt', quantity: 10}, {name: 'Plaid Back Zipper Pleated Skirt', quantity: 10}]})
            Report.create({date: new Date('2017-03-22'), product:[{name: 'Black Plaid Keyhole Front Bell Sleeve Dress', quantity: 0}, {name: 'Black Halter One Shoulder Bodycon Dress', quantity: 10}, {name: 'Black Ripped Drawstring Sweatpants', quantity: 10}, {name: 'Black Contrast Elastic Waist Faux Leather Leggings', quantity: 10}, {name: 'Silver Elastic Fabric Chunky Heel Short Boots', quantity: 10}, {name: 'White V Neck Drop Shoulder Sweater', quantity: 10}, {name: 'Pink Layered Ruffle Sleeve Pullover Sweater', quantity: 10}, {name: 'Green army jacket', quantity: 10}, {name: 'adidas navy bomber jacket', quantity: 10}, {name: 'Chain', quantity: 10}, {name: 'Turtleneck Raglan Sleeve Loose Sweater', quantity: 10}, {name: 'White Lace Overlay Elastic Waist Skirt', quantity: 10}, {name: 'Plaid Back Zipper Pleated Skirt', quantity: 10}]})
            Report.create({date: new Date('2017-03-21'), product:[{name: 'Black Plaid Keyhole Front Bell Sleeve Dress', quantity: 0}, {name: 'Black Halter One Shoulder Bodycon Dress', quantity: 10}, {name: 'Black Ripped Drawstring Sweatpants', quantity: 10}, {name: 'Black Contrast Elastic Waist Faux Leather Leggings', quantity: 10}, {name: 'Silver Elastic Fabric Chunky Heel Short Boots', quantity: 10}, {name: 'White V Neck Drop Shoulder Sweater', quantity: 10}, {name: 'Pink Layered Ruffle Sleeve Pullover Sweater', quantity: 10}, {name: 'Green army jacket', quantity: 10}, {name: 'adidas navy bomber jacket', quantity: 10}, {name: 'Chain', quantity: 10}, {name: 'Turtleneck Raglan Sleeve Loose Sweater', quantity: 10}, {name: 'White Lace Overlay Elastic Waist Skirt', quantity: 10}, {name: 'Plaid Back Zipper Pleated Skirt', quantity: 10}]})
            Report.create({date: new Date('2017-03-20'), product:[{name: 'Black Plaid Keyhole Front Bell Sleeve Dress', quantity: 0}, {name: 'Black Halter One Shoulder Bodycon Dress', quantity: 10}, {name: 'Black Ripped Drawstring Sweatpants', quantity: 10}, {name: 'Black Contrast Elastic Waist Faux Leather Leggings', quantity: 10}, {name: 'Silver Elastic Fabric Chunky Heel Short Boots', quantity: 10}, {name: 'White V Neck Drop Shoulder Sweater', quantity: 10}, {name: 'Pink Layered Ruffle Sleeve Pullover Sweater', quantity: 10}, {name: 'Green army jacket', quantity: 10}, {name: 'adidas navy bomber jacket', quantity: 10}, {name: 'Chain', quantity: 10}, {name: 'Turtleneck Raglan Sleeve Loose Sweater', quantity: 10}, {name: 'White Lace Overlay Elastic Waist Skirt', quantity: 10}, {name: 'Plaid Back Zipper Pleated Skirt', quantity: 10}]})
            Report.create({date: new Date('2017-03-19'), product:[{name: 'Black Plaid Keyhole Front Bell Sleeve Dress', quantity: 0}, {name: 'Black Halter One Shoulder Bodycon Dress', quantity: 10}, {name: 'Black Ripped Drawstring Sweatpants', quantity: 10}, {name: 'Black Contrast Elastic Waist Faux Leather Leggings', quantity: 10}, {name: 'Silver Elastic Fabric Chunky Heel Short Boots', quantity: 10}, {name: 'White V Neck Drop Shoulder Sweater', quantity: 10}, {name: 'Pink Layered Ruffle Sleeve Pullover Sweater', quantity: 10}, {name: 'Green army jacket', quantity: 10}, {name: 'adidas navy bomber jacket', quantity: 10}, {name: 'Chain', quantity: 10}, {name: 'Turtleneck Raglan Sleeve Loose Sweater', quantity: 10}, {name: 'White Lace Overlay Elastic Waist Skirt', quantity: 10}, {name: 'Plaid Back Zipper Pleated Skirt', quantity: 10}]})
            Report.create({date: new Date('2017-03-18'), product:[{name: 'Black Plaid Keyhole Front Bell Sleeve Dress', quantity: 1}, {name: 'Black Halter One Shoulder Bodycon Dress', quantity: 10}, {name: 'Black Ripped Drawstring Sweatpants', quantity: 10}, {name: 'Black Contrast Elastic Waist Faux Leather Leggings', quantity: 10}, {name: 'Silver Elastic Fabric Chunky Heel Short Boots', quantity: 10}, {name: 'White V Neck Drop Shoulder Sweater', quantity: 10}, {name: 'Pink Layered Ruffle Sleeve Pullover Sweater', quantity: 10}, {name: 'Green army jacket', quantity: 10}, {name: 'adidas navy bomber jacket', quantity: 10}, {name: 'Chain', quantity: 10}, {name: 'Turtleneck Raglan Sleeve Loose Sweater', quantity: 10}, {name: 'White Lace Overlay Elastic Waist Skirt', quantity: 10}, {name: 'Plaid Back Zipper Pleated Skirt', quantity: 10}]})
            Report.create({date: new Date('2017-03-17'), product:[{name: 'Black Plaid Keyhole Front Bell Sleeve Dress', quantity: 1}, {name: 'Black Halter One Shoulder Bodycon Dress', quantity: 10}, {name: 'Black Ripped Drawstring Sweatpants', quantity: 10}, {name: 'Black Contrast Elastic Waist Faux Leather Leggings', quantity: 10}, {name: 'Silver Elastic Fabric Chunky Heel Short Boots', quantity: 10}, {name: 'White V Neck Drop Shoulder Sweater', quantity: 10}, {name: 'Pink Layered Ruffle Sleeve Pullover Sweater', quantity: 10}, {name: 'Green army jacket', quantity: 10}, {name: 'adidas navy bomber jacket', quantity: 10}, {name: 'Chain', quantity: 10}, {name: 'Turtleneck Raglan Sleeve Loose Sweater', quantity: 10}, {name: 'White Lace Overlay Elastic Waist Skirt', quantity: 10}, {name: 'Plaid Back Zipper Pleated Skirt', quantity: 10}]})
            Report.create({date: new Date('2017-03-16'), product:[{name: 'Black Plaid Keyhole Front Bell Sleeve Dress', quantity: 2}, {name: 'Black Halter One Shoulder Bodycon Dress', quantity: 10}, {name: 'Black Ripped Drawstring Sweatpants', quantity: 10}, {name: 'Black Contrast Elastic Waist Faux Leather Leggings', quantity: 10}, {name: 'Silver Elastic Fabric Chunky Heel Short Boots', quantity: 10}, {name: 'White V Neck Drop Shoulder Sweater', quantity: 10}, {name: 'Pink Layered Ruffle Sleeve Pullover Sweater', quantity: 10}, {name: 'Green army jacket', quantity: 10}, {name: 'adidas navy bomber jacket', quantity: 10}, {name: 'Chain', quantity: 10}, {name: 'Turtleneck Raglan Sleeve Loose Sweater', quantity: 10}, {name: 'White Lace Overlay Elastic Waist Skirt', quantity: 10}, {name: 'Plaid Back Zipper Pleated Skirt', quantity: 10}]})
            Report.create({date: new Date('2017-03-15'), product:[{name: 'Black Plaid Keyhole Front Bell Sleeve Dress', quantity: 2}, {name: 'Black Halter One Shoulder Bodycon Dress', quantity: 10}, {name: 'Black Ripped Drawstring Sweatpants', quantity: 10}, {name: 'Black Contrast Elastic Waist Faux Leather Leggings', quantity: 10}, {name: 'Silver Elastic Fabric Chunky Heel Short Boots', quantity: 10}, {name: 'White V Neck Drop Shoulder Sweater', quantity: 10}, {name: 'Pink Layered Ruffle Sleeve Pullover Sweater', quantity: 10}, {name: 'Green army jacket', quantity: 10}, {name: 'adidas navy bomber jacket', quantity: 10}, {name: 'Chain', quantity: 10}, {name: 'Turtleneck Raglan Sleeve Loose Sweater', quantity: 10}, {name: 'White Lace Overlay Elastic Waist Skirt', quantity: 10}, {name: 'Plaid Back Zipper Pleated Skirt', quantity: 10}]})
            Report.create({date: new Date('2017-03-14'), product:[{name: 'Black Plaid Keyhole Front Bell Sleeve Dress', quantity: 2}, {name: 'Black Halter One Shoulder Bodycon Dress', quantity: 10}, {name: 'Black Ripped Drawstring Sweatpants', quantity: 10}, {name: 'Black Contrast Elastic Waist Faux Leather Leggings', quantity: 10}, {name: 'Silver Elastic Fabric Chunky Heel Short Boots', quantity: 10}, {name: 'White V Neck Drop Shoulder Sweater', quantity: 10}, {name: 'Pink Layered Ruffle Sleeve Pullover Sweater', quantity: 10}, {name: 'Green army jacket', quantity: 10}, {name: 'adidas navy bomber jacket', quantity: 10}, {name: 'Chain', quantity: 10}, {name: 'Turtleneck Raglan Sleeve Loose Sweater', quantity: 10}, {name: 'White Lace Overlay Elastic Waist Skirt', quantity: 10}, {name: 'Plaid Back Zipper Pleated Skirt', quantity: 10}]})
            Report.create({date: new Date('2017-03-13'), product:[{name: 'Black Plaid Keyhole Front Bell Sleeve Dress', quantity: 3}, {name: 'Black Halter One Shoulder Bodycon Dress', quantity: 10}, {name: 'Black Ripped Drawstring Sweatpants', quantity: 10}, {name: 'Black Contrast Elastic Waist Faux Leather Leggings', quantity: 10}, {name: 'Silver Elastic Fabric Chunky Heel Short Boots', quantity: 10}, {name: 'White V Neck Drop Shoulder Sweater', quantity: 10}, {name: 'Pink Layered Ruffle Sleeve Pullover Sweater', quantity: 10}, {name: 'Green army jacket', quantity: 10}, {name: 'adidas navy bomber jacket', quantity: 10}, {name: 'Chain', quantity: 10}, {name: 'Turtleneck Raglan Sleeve Loose Sweater', quantity: 10}, {name: 'White Lace Overlay Elastic Waist Skirt', quantity: 10}, {name: 'Plaid Back Zipper Pleated Skirt', quantity: 10}]})
            Report.create({date: new Date('2017-03-12'), product:[{name: 'Black Plaid Keyhole Front Bell Sleeve Dress', quantity: 3}, {name: 'Black Halter One Shoulder Bodycon Dress', quantity: 10}, {name: 'Black Ripped Drawstring Sweatpants', quantity: 10}, {name: 'Black Contrast Elastic Waist Faux Leather Leggings', quantity: 10}, {name: 'Silver Elastic Fabric Chunky Heel Short Boots', quantity: 10}, {name: 'White V Neck Drop Shoulder Sweater', quantity: 10}, {name: 'Pink Layered Ruffle Sleeve Pullover Sweater', quantity: 10}, {name: 'Green army jacket', quantity: 10}, {name: 'adidas navy bomber jacket', quantity: 10}, {name: 'Chain', quantity: 10}, {name: 'Turtleneck Raglan Sleeve Loose Sweater', quantity: 10}, {name: 'White Lace Overlay Elastic Waist Skirt', quantity: 10}, {name: 'Plaid Back Zipper Pleated Skirt', quantity: 10}]})
            Report.create({date: new Date('2017-03-11'), product:[{name: 'Black Plaid Keyhole Front Bell Sleeve Dress', quantity: 3}, {name: 'Black Halter One Shoulder Bodycon Dress', quantity: 10}, {name: 'Black Ripped Drawstring Sweatpants', quantity: 10}, {name: 'Black Contrast Elastic Waist Faux Leather Leggings', quantity: 10}, {name: 'Silver Elastic Fabric Chunky Heel Short Boots', quantity: 10}, {name: 'White V Neck Drop Shoulder Sweater', quantity: 10}, {name: 'Pink Layered Ruffle Sleeve Pullover Sweater', quantity: 10}, {name: 'Green army jacket', quantity: 10}, {name: 'adidas navy bomber jacket', quantity: 10}, {name: 'Chain', quantity: 10}, {name: 'Turtleneck Raglan Sleeve Loose Sweater', quantity: 10}, {name: 'White Lace Overlay Elastic Waist Skirt', quantity: 10}, {name: 'Plaid Back Zipper Pleated Skirt', quantity: 10}]})
            Report.create({date: new Date('2017-03-10'), product:[{name: 'Black Plaid Keyhole Front Bell Sleeve Dress', quantity: 4}, {name: 'Black Halter One Shoulder Bodycon Dress', quantity: 10}, {name: 'Black Ripped Drawstring Sweatpants', quantity: 10}, {name: 'Black Contrast Elastic Waist Faux Leather Leggings', quantity: 10}, {name: 'Silver Elastic Fabric Chunky Heel Short Boots', quantity: 10}, {name: 'White V Neck Drop Shoulder Sweater', quantity: 10}, {name: 'Pink Layered Ruffle Sleeve Pullover Sweater', quantity: 10}, {name: 'Green army jacket', quantity: 10}, {name: 'adidas navy bomber jacket', quantity: 10}, {name: 'Chain', quantity: 10}, {name: 'Turtleneck Raglan Sleeve Loose Sweater', quantity: 10}, {name: 'White Lace Overlay Elastic Waist Skirt', quantity: 10}, {name: 'Plaid Back Zipper Pleated Skirt', quantity: 10}]})
            Report.create({date: new Date('2017-03-09'), product:[{name: 'Black Plaid Keyhole Front Bell Sleeve Dress', quantity: 5}, {name: 'Black Halter One Shoulder Bodycon Dress', quantity: 10}, {name: 'Black Ripped Drawstring Sweatpants', quantity: 10}, {name: 'Black Contrast Elastic Waist Faux Leather Leggings', quantity: 10}, {name: 'Silver Elastic Fabric Chunky Heel Short Boots', quantity: 10}, {name: 'White V Neck Drop Shoulder Sweater', quantity: 10}, {name: 'Pink Layered Ruffle Sleeve Pullover Sweater', quantity: 10}, {name: 'Green army jacket', quantity: 10}, {name: 'adidas navy bomber jacket', quantity: 10}, {name: 'Chain', quantity: 10}, {name: 'Turtleneck Raglan Sleeve Loose Sweater', quantity: 10}, {name: 'White Lace Overlay Elastic Waist Skirt', quantity: 10}, {name: 'Plaid Back Zipper Pleated Skirt', quantity: 10}]})
            Report.create({date: new Date('2017-03-08'), product:[{name: 'Black Plaid Keyhole Front Bell Sleeve Dress', quantity: 5}, {name: 'Black Halter One Shoulder Bodycon Dress', quantity: 10}, {name: 'Black Ripped Drawstring Sweatpants', quantity: 10}, {name: 'Black Contrast Elastic Waist Faux Leather Leggings', quantity: 10}, {name: 'Silver Elastic Fabric Chunky Heel Short Boots', quantity: 10}, {name: 'White V Neck Drop Shoulder Sweater', quantity: 10}, {name: 'Pink Layered Ruffle Sleeve Pullover Sweater', quantity: 10}, {name: 'Green army jacket', quantity: 10}, {name: 'adidas navy bomber jacket', quantity: 10}, {name: 'Chain', quantity: 10}, {name: 'Turtleneck Raglan Sleeve Loose Sweater', quantity: 10}, {name: 'White Lace Overlay Elastic Waist Skirt', quantity: 10}, {name: 'Plaid Back Zipper Pleated Skirt', quantity: 10}]})
            Report.create({date: new Date('2017-03-07'), product:[{name: 'Black Plaid Keyhole Front Bell Sleeve Dress', quantity: 5}, {name: 'Black Halter One Shoulder Bodycon Dress', quantity: 10}, {name: 'Black Ripped Drawstring Sweatpants', quantity: 10}, {name: 'Black Contrast Elastic Waist Faux Leather Leggings', quantity: 10}, {name: 'Silver Elastic Fabric Chunky Heel Short Boots', quantity: 10}, {name: 'White V Neck Drop Shoulder Sweater', quantity: 10}, {name: 'Pink Layered Ruffle Sleeve Pullover Sweater', quantity: 10}, {name: 'Green army jacket', quantity: 10}, {name: 'adidas navy bomber jacket', quantity: 10}, {name: 'Chain', quantity: 10}, {name: 'Turtleneck Raglan Sleeve Loose Sweater', quantity: 10}, {name: 'White Lace Overlay Elastic Waist Skirt', quantity: 10}, {name: 'Plaid Back Zipper Pleated Skirt', quantity: 10}]})
            Report.create({date: new Date('2017-03-06'), product:[{name: 'Black Plaid Keyhole Front Bell Sleeve Dress', quantity: 8}, {name: 'Black Halter One Shoulder Bodycon Dress', quantity: 10}, {name: 'Black Ripped Drawstring Sweatpants', quantity: 10}, {name: 'Black Contrast Elastic Waist Faux Leather Leggings', quantity: 10}, {name: 'Silver Elastic Fabric Chunky Heel Short Boots', quantity: 10}, {name: 'White V Neck Drop Shoulder Sweater', quantity: 10}, {name: 'Pink Layered Ruffle Sleeve Pullover Sweater', quantity: 10}, {name: 'Green army jacket', quantity: 10}, {name: 'adidas navy bomber jacket', quantity: 10}, {name: 'Chain', quantity: 10}, {name: 'Turtleneck Raglan Sleeve Loose Sweater', quantity: 10}, {name: 'White Lace Overlay Elastic Waist Skirt', quantity: 10}, {name: 'Plaid Back Zipper Pleated Skirt', quantity: 10}]})
            Report.create({date: new Date('2017-03-05'), product:[{name: 'Black Plaid Keyhole Front Bell Sleeve Dress', quantity: 8}, {name: 'Black Halter One Shoulder Bodycon Dress', quantity: 10}, {name: 'Black Ripped Drawstring Sweatpants', quantity: 10}, {name: 'Black Contrast Elastic Waist Faux Leather Leggings', quantity: 10}, {name: 'Silver Elastic Fabric Chunky Heel Short Boots', quantity: 10}, {name: 'White V Neck Drop Shoulder Sweater', quantity: 10}, {name: 'Pink Layered Ruffle Sleeve Pullover Sweater', quantity: 10}, {name: 'Green army jacket', quantity: 10}, {name: 'adidas navy bomber jacket', quantity: 10}, {name: 'Chain', quantity: 10}, {name: 'Turtleneck Raglan Sleeve Loose Sweater', quantity: 10}, {name: 'White Lace Overlay Elastic Waist Skirt', quantity: 10}, {name: 'Plaid Back Zipper Pleated Skirt', quantity: 10}]})
            Report.create({date: new Date('2017-03-04'), product:[{name: 'Black Plaid Keyhole Front Bell Sleeve Dress', quantity: 8}, {name: 'Black Halter One Shoulder Bodycon Dress', quantity: 10}, {name: 'Black Ripped Drawstring Sweatpants', quantity: 10}, {name: 'Black Contrast Elastic Waist Faux Leather Leggings', quantity: 10}, {name: 'Silver Elastic Fabric Chunky Heel Short Boots', quantity: 10}, {name: 'White V Neck Drop Shoulder Sweater', quantity: 10}, {name: 'Pink Layered Ruffle Sleeve Pullover Sweater', quantity: 10}, {name: 'Green army jacket', quantity: 10}, {name: 'adidas navy bomber jacket', quantity: 10}, {name: 'Chain', quantity: 10}, {name: 'Turtleneck Raglan Sleeve Loose Sweater', quantity: 10}, {name: 'White Lace Overlay Elastic Waist Skirt', quantity: 10}, {name: 'Plaid Back Zipper Pleated Skirt', quantity: 10}]})
            Report.create({date: new Date('2017-03-03'), product:[{name: 'Black Plaid Keyhole Front Bell Sleeve Dress', quantity: 9}, {name: 'Black Halter One Shoulder Bodycon Dress', quantity: 10}, {name: 'Black Ripped Drawstring Sweatpants', quantity: 10}, {name: 'Black Contrast Elastic Waist Faux Leather Leggings', quantity: 10}, {name: 'Silver Elastic Fabric Chunky Heel Short Boots', quantity: 10}, {name: 'White V Neck Drop Shoulder Sweater', quantity: 10}, {name: 'Pink Layered Ruffle Sleeve Pullover Sweater', quantity: 10}, {name: 'Green army jacket', quantity: 10}, {name: 'adidas navy bomber jacket', quantity: 10}, {name: 'Chain', quantity: 10}, {name: 'Turtleneck Raglan Sleeve Loose Sweater', quantity: 10}, {name: 'White Lace Overlay Elastic Waist Skirt', quantity: 10}, {name: 'Plaid Back Zipper Pleated Skirt', quantity: 10}]})
            Report.create({date: new Date('2017-03-02'), product:[{name: 'Black Plaid Keyhole Front Bell Sleeve Dress', quantity: 10}, {name: 'Black Halter One Shoulder Bodycon Dress', quantity: 10}, {name: 'Black Ripped Drawstring Sweatpants', quantity: 10}, {name: 'Black Contrast Elastic Waist Faux Leather Leggings', quantity: 10}, {name: 'Silver Elastic Fabric Chunky Heel Short Boots', quantity: 10}, {name: 'White V Neck Drop Shoulder Sweater', quantity: 10}, {name: 'Pink Layered Ruffle Sleeve Pullover Sweater', quantity: 10}, {name: 'Green army jacket', quantity: 10}, {name: 'adidas navy bomber jacket', quantity: 10}, {name: 'Chain', quantity: 10}, {name: 'Turtleneck Raglan Sleeve Loose Sweater', quantity: 10}, {name: 'White Lace Overlay Elastic Waist Skirt', quantity: 10}, {name: 'Plaid Back Zipper Pleated Skirt', quantity: 10}]})
            Report.create({date: new Date('2017-03-01'), product:[{name: 'Black Plaid Keyhole Front Bell Sleeve Dress', quantity: 10}, {name: 'Black Halter One Shoulder Bodycon Dress', quantity: 10}, {name: 'Black Ripped Drawstring Sweatpants', quantity: 10}, {name: 'Black Contrast Elastic Waist Faux Leather Leggings', quantity: 10}, {name: 'Silver Elastic Fabric Chunky Heel Short Boots', quantity: 10}, {name: 'White V Neck Drop Shoulder Sweater', quantity: 10}, {name: 'Pink Layered Ruffle Sleeve Pullover Sweater', quantity: 10}, {name: 'Green army jacket', quantity: 10}, {name: 'adidas navy bomber jacket', quantity: 10}, {name: 'Chain', quantity: 10}, {name: 'Turtleneck Raglan Sleeve Loose Sweater', quantity: 10}, {name: 'White Lace Overlay Elastic Waist Skirt', quantity: 10}, {name: 'Plaid Back Zipper Pleated Skirt', quantity: 10}]})
        }
    })
}

//exports default products function so app can run when it starts
exports.createDefaultReport = createDefaultReport;
